name: resolvi
channels:
  - conda-forge
  - bioconda
  - pytorch
dependencies:
  - python=3.9
  - scanpy=1.9.6
  - scvi-tools=1.0.4
  - decoupler=1.4.0
  - matplotlib=3.7.1
  - seaborn=0.12.2
  - pandas=2.0.3
  - numpy=1.24.3
  - scipy=1.11.1
  - scikit-learn=1.3.0
  - anndata=0.9.2
  - h5py=3.9.0
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - lightning=2.0.0
  - jax=0.4.13
  - jaxlib=0.4.13
  - numba=0.57.1
  - networkx=3.1
  - statsmodels=0.14.0
  - adjusttext=0.7.3
  - plotly=5.15.0
  - markdown=3.4.4
  - pip=23.2.1
  - pip:
    - mudata>=0.2.3
    - omnipath>=1.0.6

