---
# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-resolvinf-1.0dev
channels: [conda-forge, bioconda, defaults]
dependencies:
  - conda-forge::python=3.9
  - conda-forge::markdown=3.4.4
  - conda-forge::pymdown-extensions=9.5
  - conda-forge::pygments=2.13.0
  # Core dependencies
  - bioconda::scanpy=1.9.3
  - bioconda::scvi-tools=1.0.4
  - conda-forge::spatialdata=0.0.14
  - bioconda::decoupler=1.4.0
  # Visualization
  - conda-forge::matplotlib=3.6.2
  - conda-forge::seaborn=0.12.1
  # Utilities
  - bioconda::multiqc=1.14
  - conda-forge::pandas=1.5.2
  - conda-forge::numpy=1.24.1
  # GPU support
  - pytorch::pytorch=2.0.1
  - pytorch::pytorch-cuda=11.8
